language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "python-3.6"
      env: PY=3.6
    - name: "python-3.7"
      env: PY=3.7

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda env create --name TEST python=$PY --file environment.yml
    source activate TEST
    conda info --all
    mkdir -p ~/.fonts/
    cp -rf \{\{\ cookiecutter.repo_name\ \}\}/paper/.pandoc/fonts/* ~/.fonts/

script:
  - if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      travis_wait 45 pytest; 
    fi

notifications:
    email:
        recipients:
            - ek@knaaptime.com 
        on_success: change
        on_failure: always 
